name: 'Git HTTPS push deploy'
description: 'Simple HTTPS Git master branch push for e.g. Heroku or Gigalixir deploys'
author: 'Ilkka Poutanen <ilkka@ilkka.dev>'
branding:
  color: 'yellow'
  icon: 'arrow-up'
inputs:
  remoteUrl:
    description: 'Origin to push to'
    required: true
  forcePush:
    description: 'Use --force on git push'
    required: false
    default: false
  skipHooks:
    description: 'Skip git hooks with --no-verify'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SKIP_HOOKS: ${{ inputs.skipHooks }}
    FORCE_PUSH: ${{ inputs.forcePush }}
  args:
    - ${{ inputs.remoteUrl }}
